// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBWojSW1KtHxnSHt1paw53hSxI49ii-g4',
    appId: '1:675598710080:web:bc2453d74c0e82d20bb6a5',
    messagingSenderId: '675598710080',
    projectId: 'grow-up-50a68',
    authDomain: 'grow-up-50a68.firebaseapp.com',
    storageBucket: 'grow-up-50a68.firebasestorage.app',
    measurementId: 'G-0YQHC4FM0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJheoV50FUP3i21PEwkMjim5ztozf48Q0',
    appId: '1:675598710080:android:bcfdb933ecac716a0bb6a5',
    messagingSenderId: '675598710080',
    projectId: 'grow-up-50a68',
    storageBucket: 'grow-up-50a68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKjloMpFwpb8NF4PYWseGSPsESo2iJ2PE',
    appId: '1:675598710080:ios:4cf56b91272260310bb6a5',
    messagingSenderId: '675598710080',
    projectId: 'grow-up-50a68',
    storageBucket: 'grow-up-50a68.firebasestorage.app',
    iosBundleId: 'com.example.growUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKjloMpFwpb8NF4PYWseGSPsESo2iJ2PE',
    appId: '1:675598710080:ios:4cf56b91272260310bb6a5',
    messagingSenderId: '675598710080',
    projectId: 'grow-up-50a68',
    storageBucket: 'grow-up-50a68.firebasestorage.app',
    iosBundleId: 'com.example.growUp',
  );

}